export const constants = {
	version: 'v6.3.6 beta',
	shortcuts: {
		65  : 'add',
		68  : 'delete',
		70  : 'add folder',
		77  : 'edit mode',
		73  : 'import',
		69  : 'export',
		83  : 'save',
		72  : 'help',
		82  : 'revert',
		81  : 'quit',
		79  : 'other',
		80  : 'placemarks',
		219 : 'other placemarks',
		67  : 'center',
		27  : 'close',
		37  : 'left',
		39  : 'right',
		90  : 'undo',
		89  : 'redo',
	},
	dirs: {
		uploads: {
			images: {
				big: '/uploads/images/big/',
				small: '/uploads/images/small/',
				orphanedbig: '/uploads/images/big/orphaned/',
				orphanedsmall: '/uploads/images/small/orphaned/',
			},
		},
	},
	sessionlifetime: 3600,
	backupscount: 10,
	commonplacesonpagecount: 5,
	commonroutesonpagecount: 5,
	map: {
		initial: {
			latitude  : 0,
			longitude : 0,
			zoom      : 15,
		},
		precision: 7,
	},
	sidebars: {
		top    : { act: 95, min: 0, max: Infinity },
		right  : { act: 250, min: 0, max: Infinity },
		bottom : { act: 57, min: 0, max: Infinity },
		left   : { act: 250, min: 0, max: Infinity },
		center : { min: 200 },
	},
	sidebarsCompact: {
		top    : { act: 80, min: 0, max: Infinity },
		right  : { act: 200, min: 0, max: Infinity },
		bottom : { act: 95, min: 0, max: Infinity },
		left   : { act: 200, min: 0, max: Infinity },
		center : { min: 200 },
	},
	sidebarsCompactUltra: {
		top    : { act: 80, min: 0, max: Infinity },
		right  : { act: 0, min: 0, max: Infinity },
		bottom : { act: 95, min: 0, max: Infinity },
		left   : { act: 0, min: 0, max: Infinity },
		center : { min: 200 },
	},
	compact: 1000,
	compactUltra: 800,
	earthRadius: 6371,
	links: {
		service: 'https://places.scrofa-tridens.ru/',
		repository: 'https://github.com/assador/places',
		contacts: {
			email: 'mailto:places@scrofa-tridens.ru',
		},
		publications: {
			habr: 'https://habr.com/ru/articles/1009226/',
		},
		donate: {
			boosty: 'https://boosty.to/assador/donate',
		},
	},
};
