export const treeSorted = [
	{
		"id": "EsHS1i213EDZj2D7gl0JsA05vFFbICPB",
		"parent": null,
		"context": "places",
		"name": "Москва",
		"description": "Всякие места в Москве",
		"srt": 1,
		"geomarks": 1,
		"userid": "yJ02ELehJphCRMpYoOfXsHyK3vY6oGbd",
		"type": "folder",
		"added": false,
		"deleted": false,
		"updated": false,
		"open": true,
		"children": {
			"36vP5nlPrl7F0nYFY08goIu6h8WQnfhg": {
				"id": "36vP5nlPrl7F0nYFY08goIu6h8WQnfhg",
				"parent": "EsHS1i213EDZj2D7gl0JsA05vFFbICPB",
				"context": "places",
				"name": "Гос. структуры",
				"description": "Отделения государственных структур",
				"srt": 1,
				"geomarks": 1,
				"userid": "yJ02ELehJphCRMpYoOfXsHyK3vY6oGbd",
				"type": "folder",
				"added": false,
				"deleted": false,
				"updated": false,
				"open": false,
				"builded": true,
			},
			"0hYL8cQOxG82aFYZMfgYhWVivbyM66ye": {
				"id": "0hYL8cQOxG82aFYZMfgYhWVivbyM66ye",
				"parent": "EsHS1i213EDZj2D7gl0JsA05vFFbICPB",
				"context": "places",
				"name": "Магазины",
				"description": "",
				"srt": 5,
				"geomarks": 1,
				"userid": "yJ02ELehJphCRMpYoOfXsHyK3vY6oGbd",
				"type": "folder",
				"added": false,
				"deleted": false,
				"updated": false,
				"open": false,
				"builded": true,
			},
		},
		"builded": true,
	},
	{
		"id": "nBG5TLsWKccf44h4UzUl6IznRDFfLmaY",
		"parent": null,
		"context": "places",
		"name": "Походы",
		"description": "Походные места",
		"srt": 1.5,
		"geomarks": 1,
		"userid": "yJ02ELehJphCRMpYoOfXsHyK3vY6oGbd",
		"type": "folder",
		"added": false,
		"deleted": false,
		"updated": false,
		"open": false,
		"children": {
			"fspYd0udMc1CjjSREoS38wOaUCj96NJZ": {
				"id": "fspYd0udMc1CjjSREoS38wOaUCj96NJZ",
				"parent": "nBG5TLsWKccf44h4UzUl6IznRDFfLmaY",
				"context": "places",
				"name": "Алтай",
				"description": "",
				"srt": 0.75,
				"geomarks": 1,
				"userid": "yJ02ELehJphCRMpYoOfXsHyK3vY6oGbd",
				"type": "folder",
				"added": false,
				"deleted": false,
				"updated": false,
				"open": false,
				"children": {
					"0RXjhvu7ZdEjXvID8hAXizLjC9RFSCny": {
						"id": "0RXjhvu7ZdEjXvID8hAXizLjC9RFSCny",
						"parent": "fspYd0udMc1CjjSREoS38wOaUCj96NJZ",
						"context": "places",
						"name": "Катунь 2008",
						"description": "Сплав по Катуни на катамаране с Бородеем, Андрюхой, Энерджайзером и Саней.",
						"srt": 3.03125,
						"geomarks": 1,
						"userid": "yJ02ELehJphCRMpYoOfXsHyK3vY6oGbd",
						"type": "folder",
						"added": false,
						"deleted": false,
						"updated": false,
						"open": false,
						"builded": true,
					},
				},
				"builded": true,
			},
			"HDvAVlozgwYEbIJVgvZE7JQhYQM5Oc1E": {
				"id": "HDvAVlozgwYEbIJVgvZE7JQhYQM5Oc1E",
				"parent": "nBG5TLsWKccf44h4UzUl6IznRDFfLmaY",
				"context": "places",
				"name": "Кольский п-ов",
				"description": "Кольский полуостров",
				"srt": 1.5,
				"geomarks": 1,
				"userid": "yJ02ELehJphCRMpYoOfXsHyK3vY6oGbd",
				"type": "folder",
				"added": false,
				"deleted": false,
				"updated": false,
				"open": false,
				"children": {
					"8rICT3hwaR5jjZzzMfoZo6nJXFAWYzKt": {
						"id": "8rICT3hwaR5jjZzzMfoZo6nJXFAWYzKt",
						"parent": "HDvAVlozgwYEbIJVgvZE7JQhYQM5Oc1E",
						"context": "places",
						"name": "Ловозёры",
						"description": "",
						"srt": 6,
						"geomarks": 1,
						"userid": "yJ02ELehJphCRMpYoOfXsHyK3vY6oGbd",
						"type": "folder",
						"added": false,
						"deleted": false,
						"updated": false,
						"open": false,
						"builded": true,
					},
					"2jmi6ciMRxs0pSVUSUBxwdROjAfeWBcf": {
						"id": "2jmi6ciMRxs0pSVUSUBxwdROjAfeWBcf",
						"parent": "HDvAVlozgwYEbIJVgvZE7JQhYQM5Oc1E",
						"context": "places",
						"name": "Хибины",
						"description": "",
						"srt": 3,
						"geomarks": 1,
						"userid": "yJ02ELehJphCRMpYoOfXsHyK3vY6oGbd",
						"type": "folder",
						"added": false,
						"deleted": false,
						"updated": false,
						"open": false,
						"builded": true,
					},
				},
				"builded": true,
			},
		},
		"builded": true,
	},
	{
		"id": "BO4xIkgGi58m4J2ptfXFB9x5ZleqY9WV",
		"parent": null,
		"context": "places",
		"name": "Работа",
		"description": "",
		"srt": 5,
		"geomarks": 1,
		"userid": "yJ02ELehJphCRMpYoOfXsHyK3vY6oGbd",
		"type": "folder",
		"added": false,
		"deleted": false,
		"updated": false,
		"open": false,
		"builded": true,
	},
	{
		"id": "4cHwO9Qg35qK1cwN0cl2xLV74AkFOUSx",
		"parent": null,
		"context": "places",
		"name": "Ребуха",
		"description": "",
		"srt": 6,
		"geomarks": 1,
		"userid": "yJ02ELehJphCRMpYoOfXsHyK3vY6oGbd",
		"type": "folder",
		"added": false,
		"deleted": false,
		"updated": false,
		"open": false,
		"builded": true,
	},
];
